// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uadhbuismeowtfipifve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZGhidWlzbWVvd3RmaXBpZnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDk0ODQsImV4cCI6MjA3MzQyNTQ4NH0.AtRk82tJ2yIJehw_WVcWCA5lmRbUDMdMoS3IuQL9kZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});